first time submitted for verification
Nikita-Fast/Homework pull request #6
Opened 2019-12-15 18:32 UTC by Nikita-Fast

2019-12-17 15:31 UTC, Maksim-Zhuravlev requested changes

2019-12-17 15:31 UTC, Maksim-Zhuravlev commented on Interface.c
> +	while (numberOfOperation != 10) {
Magic numbers

2019-12-17 15:31 UTC, Maksim-Zhuravlev commented on listLibrary.c
> +	struct List list;
У этой переменной область видимости до выхода из блока, а вы его возвращаете в качестве результата.

2019-12-17 15:31 UTC, Maksim-Zhuravlev commented on listLibrary.c
> +	if (listPtr->length == 2) {
А вставить на последнее место через вставку после мы можем только при длине списка 1?

2019-12-17 15:31 UTC, Maksim-Zhuravlev commented on listLibrary.c
> +	if (listPtr->head == delNodePtr) {
А если удаляемый был последним?

2019-12-17 15:31 UTC, Maksim-Zhuravlev commented on Interface.c
> +		case 1:
Magic numbers

2019-12-17 15:31 UTC, Maksim-Zhuravlev commented on Interface.c
> +			printf("Enter the address of element and the address of the list\n");
Работать с адресами памяти, вводимыми с клавиатуры, в данной задаче - опасная идея.
Безопаснее оперировать позициями в списке: вставить после i-го, удалить i-ый или удалить первый найденный со значением равным данному.

2019-12-23 22:58 UTC, Maksim-Zhuravlev requested changes

2019-12-23 22:58 UTC, Maksim-Zhuravlev commented on listLibrary.c
> +	struct List* list = (struct List*)malloc(sizeof(struct List));
Проверка на успешность.

2019-12-23 22:58 UTC, Maksim-Zhuravlev commented on Interface.c
> +			printf("List was successfully created, his address is %p\n", list);
his -> its

2019-12-23 22:58 UTC, Maksim-Zhuravlev commented on Interface.c
>  	colorOutput(hConsole, blue);
При выходе надо очистить список. Его могли не очистить вручную.

2019-12-24 20:55 UTC, Maksim-Zhuravlev requested changes

2019-12-24 20:55 UTC, Maksim-Zhuravlev commented on Interface.c
> +			insertToEnd(listOfAddresses, node);
Вставляете в listOfAdresses,  двумя строками выше создали list. Зачем?
При неуспешности выделения памяти createList не завершает всю программу, а возвращает NULL. Вы в этот NULL можете попытаться вставить созданный только узел, который тоже может быть NULL.

2019-12-24 21:42 UTC, Nikita-Fast commented on Interface.c
> +			insertToEnd(listOfAddresses, node);
Идея заключалась в том, чтобы создать список listOfAddresses, в котором будут храниться адреса всех успешно созданных списков и при выходе из интерфейса очистить все созданные листы и освободить память. list используется как переменная внутри switch для нужд блоков кода с case. Замечание про NULL понял.

2021-08-19 19:06 UTC, merged